spring:
  kafka:
    bootstrap-servers: 'localhost:9092'
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: kafka
      port: 27017
      host: localhost
server:
  port: 8082
